apiVersion: v1
kind: Service
metadata:
  name: hello-world-ts
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: hello-world-ts
      port: 5000
  selector:
    app: hello-world-ts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-ts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-ts
  template:
    metadata:
      labels:
        app: hello-world-ts
    spec:
      containers:
        - image: registry.cloud.okteto.net/ci7lus/hello-world:latest
          name: hello-world-ts
          resources:
            requests:
              cpu: 0.1
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          ports:
            - containerPort: 5000
